# Generated by Django 5.1.2 on 2024-11-17 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rawmaterial",
            name="SKU",
            field=models.CharField(max_length=50),
        ),
    ]
