# Generated by Django 5.1.2 on 2024-11-22 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_alter_rawmaterial_quantity"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="transaction",
            options={"ordering": ["-transaction_date"]},
        ),
    ]
