# Generated by Django 5.1.2 on 2024-11-23 01:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0007_alter_transaction_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="billofmaterials",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="bomitem",
            name="bom",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bomitem_set",
                to="catalog.billofmaterials",
            ),
        ),
    ]
